// Master Indian States, Districts, and Police Stations Directory
// Automatically compiled with statutory data from CCTNS & UP Police Directorate Directory

export const ALL_INDIAN_STATES = [
  "Uttar Pradesh",
  "Delhi",
  "Maharashtra",
  "Karnataka",
  "Tamil Nadu",
  "Gujarat",
  "Rajasthan",
  "West Bengal",
  "Bihar",
  "Madhya Pradesh",
  "Haryana",
  "Punjab",
  "Telangana",
  "Andhra Pradesh",
  "Kerala",
  "Uttarakhand",
  "Jharkhand",
  "Chhattisgarh",
  "Odisha",
  "Assam",
  "Himachal Pradesh",
  "Goa",
  "Jammu & Kashmir",
  "Tripura",
  "Manipur",
  "Meghalaya",
  "Nagaland",
  "Arunachal Pradesh",
  "Mizoram",
  "Sikkim"
];

export const CIVIC_POLICE_DIRECTORIES = {
  "Uttar Pradesh": {
    "Agra": [
      "Achhnera Police Station",
      "Agra-sector (vigilance Estt.) Police Station",
      "Anti Power Theft Thana Agra",
      "Bah Police Station",
      "Barhan Police Station",
      "Basai Arela Police Station",
      "Basai Jagner Police Station",
      "Basauni Police Station",
      "Chhatta Police Station",
      "Chitrahat Police Station",
      "Cyber Crime P.s Agra Police Station",
      "Dauki Police Station",
      "Etmadaula Police Station",
      "Etmadpur Police Station",
      "Fatehabad Police Station",
      "Fatehpur Sikri Police Station",
      "GRP Agra Cantt Police Station",
      "GRP Agra Fort Police Station",
      "Hari Parvat Police Station",
      "Iradat Nagar Police Station",
      "Jagdishpura Police Station",
      "Jagner Police Station",
      "Jaitpur Police Station",
      "Jiwanimandi Police Station",
      "Kagaraul Police Station",
      "Kamla Nagar Police Station",
      "Khandauli Police Station",
      "Khera Rathore Police Station",
      "Kheragarh Police Station",
      "Kotwali Police Station",
      "Lohamandi Police Station",
      "Madan Mohan Gate Police Station",
      "Mahila Thana",
      "Malpura Police Station",
      "Mansukhpura Police Station",
      "Mantola Police Station",
      "Nai-ki-mandi Police Station",
      "New Agra Police Station",
      "Nibora Police Station",
      "Pidhora Police Station",
      "Pinahat Police Station",
      "Rakabaganj Police Station",
      "Sadar Bazar Police Station",
      "Saiyan Police Station",
      "Shahganj Police Station",
      "Shamsabad Police Station",
      "Sikandra Police Station",
      "Tajganj Police Station",
      "Tourism Police Station"
    ],
    "Aligarh": [
      "Akrabad Police Station",
      "Atrauli Police Station",
      "Bannadevi Police Station",
      "Barla Police Station",
      "Chandaus Police Station",
      "Chandpa Police Station",
      "Chharra Police Station",
      "Civil Lines Police Station",
      "Cyber Crime P.s Aligarh Police Station",
      "Dadon Police Station",
      "Delhi Gate Police Station",
      "GRP Aligarh Police Station",
      "Gabhana Police Station",
      "Gandhi Park Police Station",
      "Gangiri Police Station",
      "Gonda Police Station",
      "Harduaganj Police Station",
      "Hathras Gate Police Station",
      "Hathras Junction Police Station",
      "Hathras Police Station",
      "Iglas Police Station",
      "Jawan Police Station",
      "Khair Police Station",
      "Kotwali Police Station",
      "Lodha Police Station",
      "Madrak Police Station",
      "Mahila Thana",
      "Mahua Kheda Police Station",
      "Palimukimpur Police Station",
      "Pisawa Police Station",
      "Qwarsi Police Station",
      "Roravar Police Station",
      "Saikandra Rao Police Station",
      "Sasni Gate Police Station",
      "Sasni Police Station",
      "Tappal Police Station",
      "Vijaygarh Police Station"
    ],
    "Ambedkar Nagar": [
      "Ahirauli Police Station",
      "Akbarpur Police Station",
      "Alapur Police Station",
      "Aliganj Police Station",
      "Baskhari Police Station",
      "Bewana Police Station",
      "Bhiti Police Station",
      "G R P Akbarpur Police Station",
      "Hanswar Police Station",
      "Ibrahimpur Police Station",
      "Jaitpur Police Station",
      "Jalalpur Police Station",
      "Jehangirganj Police Station",
      "Katka Police Station",
      "Mahila Thana",
      "Mahrua Police Station",
      "Malipur Police Station",
      "Rajesultanpur Police Station",
      "Sammanpur Police Station",
      "Tanda Police Station"
    ],
    "Amroha": [
      "(Amroha) Adampur Police Station",
      "(Amroha) Amroha Dehat Police Station",
      "(Amroha) Amroha Nagar Police Station",
      "(Amroha) Bachhraon Police Station",
      "(Amroha) Chhajlet Police Station",
      "(Amroha) Didauli Police Station",
      "(Amroha) Gajraula Police Station",
      "(Amroha) Hasanpur Police Station",
      "(Amroha) Kanth Police Station",
      "(Amroha) Mahila Thana",
      "(Amroha) Mandi Dhanaura Police Station",
      "(Amroha) Naugawan Sadat Police Station",
      "(Amroha) Rajjabpur Police Station",
      "(Amroha) Rehra Police Station",
      "(Amroha) Said Nagli Police Station"
    ],
    "Auraiya": [
      "Achhalda Police Station",
      "Ajitmal Police Station",
      "Auraiya Police Station",
      "Ayana Police Station",
      "Bela Police Station",
      "Bidhuna Police Station",
      "Dibiyapur Police Station",
      "Erwa Katra Police Station",
      "G.R.P. Phaphund Police Station",
      "Kotwali Auraiya Police Station",
      "Mahila Police Station Auraiya",
      "Phaphoond Police Station",
      "Sahayal Police Station"
    ],
    "Ayodhya (Faizabad)": [
      "Akbarpur Police Station",
      "Alapur Police Station",
      "Ayodhya Police Station",
      "Baskhari Police Station",
      "Bewana Police Station",
      "Bhiti Police Station",
      "Bikapur Police Station",
      "Cantt Police Station",
      "Gosainganj Police Station",
      "Haiderganj Police Station",
      "Hanswar Police Station",
      "Ibrahimpur Police Station",
      "Inayat Nagar Police Station",
      "Jahangirganj Police Station",
      "Jaitpur Police Station",
      "Jalalpur Police Station",
      "Khandasa Police Station",
      "Kotwali Nagar Police Station",
      "Kumar Ganj Police Station",
      "Mahila Thana",
      "Mahraj Ganj Police Station",
      "Malipur Police Station",
      "Mawai Police Station",
      "Patranga Police Station",
      "Purakalandar Police Station",
      "Raje Sultanpur Police Station",
      "Ramjanam Bhumi Police Station",
      "Ronahi Police Station",
      "Rudauli Police Station",
      "Samanpur Police Station",
      "Tanda Police Station",
      "Tarun Police Station"
    ],
    "Azamgarh": [
      "Ahiraula Police Station",
      "Akhandnagar Police Station",
      "Amethi Police Station",
      "Atraulia Police Station",
      "Baldi Rai Police Station",
      "Bardah Police Station",
      "Bazar Shukul Police Station",
      "Bilariyaganj Police Station",
      "Chanda Police Station",
      "Deogaon Police Station",
      "Dhammaur Police Station",
      "Didarganj Police Station",
      "Dostpur Police Station",
      "Gambhirpur Police Station",
      "Gauriganj Police Station",
      "Gusaiganj Police Station",
      "Haliapur Police Station",
      "Jagdishpur Police Station",
      "Jahanaganj Police Station",
      "Jaisinghpur Police Station",
      "Jamo Police Station",
      "Jeanpur Police Station",
      "Kadipur Police Station",
      "Kamroli Police Station",
      "Kandhrapur Police Station",
      "Kaptan Ganj Police Station",
      "Karodikala Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Police Station",
      "Kurebhar Police Station",
      "Kurwar Police Station",
      "Lambhua Police Station",
      "Maharajganj Police Station",
      "Mahila Thana",
      "Mehnagar Police Station",
      "Mehnajpur Police Station",
      "Motigarpur Police Station",
      "Mubarkpur Police Station",
      "Munshiganj Police Station",
      "Musafirkhana Police Station",
      "Nizamabad Police Station",
      "Pawai Police Station",
      "Phoolpur Police Station",
      "Piperpur Police Station",
      "Rani Ki Sarai Police Station",
      "Raunapar Police Station",
      "Sangrampur Police Station",
      "Saraimeer Police Station",
      "Sidhari Police Station",
      "Tahabarpur Police Station",
      "Tarwa Police Station"
    ],
    "Baghpat": [
      "Baghpat Police Station",
      "Balaini Police Station",
      "Baraut Police Station",
      "Binauli Police Station",
      "Chandi Nagar Police Station",
      "Chhaprauli Police Station",
      "Doghat Police Station",
      "G.R.P. Baraut Police Station",
      "Khekra Police Station",
      "Mahila Thana, Baghpat",
      "Ramala Police Station",
      "Singhwali Ahir Police Station"
    ],
    "Bahraich": [
      "Anti Human Trafficking Unit Police Station",
      "Baundi Police Station",
      "Bhinga Police Station",
      "Dargahsareef Police Station",
      "Fakarpur Police Station",
      "GRP Bahraich Police Station",
      "Gilaula Police Station",
      "Hardi Police Station",
      "Huzourpur Police Station",
      "Ikauna Police Station",
      "Jarwal Road Police Station",
      "Kaisherganj Police Station",
      "Khairighat Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Nagar Police Station",
      "Mahila Thana",
      "Malhipur Police Station",
      "Matera Police Station",
      "Motipur Police Station",
      "Murthiha Police Station",
      "Nanpara Police Station",
      "Nawabganj Police Station",
      "Pyagpur Police Station",
      "Ramgaon Police Station",
      "Ranipur Police Station",
      "Risia Police Station",
      "Rupai Diha Police Station",
      "Sirsia Police Station",
      "Sonwa Police Station",
      "Sujauli Police Station",
      "Visesar Ganj Police Station"
    ],
    "Ballia": [
      "Anti Power Theft Thana Ballia",
      "Anti-human Trafficking Unit Police Station",
      "Bairia Police Station",
      "Bansdih Police Station",
      "Bansdih Road Police Station",
      "Bhimpura Police Station",
      "Bhinga Police Station",
      "Chitwara Goan Police Station",
      "Dokati Police Station",
      "Dubhar Police Station",
      "GRP Ballia Police Station",
      "Gadwar Police Station",
      "Gilaula Police Station",
      "Haldi Police Station",
      "Ikauna Police Station",
      "Khejuri Police Station",
      "Kotwali Police Station",
      "Mahila Thana",
      "Malhipur Police Station",
      "Maniar Police Station",
      "Nagra Police Station",
      "Narhi Police Station",
      "Pakari Police Station",
      "Payagpur Police Station",
      "Phephana Police Station",
      "Rasra Police Station",
      "Reoti Police Station",
      "Sahatwar Police Station",
      "Sikanderpur Police Station",
      "Sirsia Police Station",
      "Sonwa Police Station",
      "Sukhpura Police Station",
      "Ubhaon Police Station",
      "Visesarganj Police Station"
    ],
    "Balrampur": [
      "Balrampur Dehat Police Station",
      "Balrampur Nagar Police Station",
      "Gaisari Police Station",
      "Gaura Chauraha Police Station",
      "Harriya Police Station",
      "Jarwa Police Station",
      "Laliya Police Station",
      "Maharajganj Tarai Police Station",
      "Mahila Thana",
      "Pachpedwa Police Station",
      "Rehra Bazaar Police Station",
      "Sadulla Nagar Police Station",
      "Tulsipur Police Station",
      "Utraula Police Station"
    ],
    "Banda": [
      "Atarra Police Station",
      "Baberu Police Station",
      "Badausa Police Station",
      "Bahil Purwa Police Station",
      "Bargarh Police Station",
      "Bissenda Police Station",
      "Chilla Police Station",
      "Fatehganj Police Station",
      "GRP Banda Police Station",
      "Girwan Police Station",
      "Jaspura Police Station",
      "Kalinjar Police Station",
      "Kamasin Police Station",
      "Karwi Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Nagar Police Station",
      "Mahila Thana",
      "Manikpur Police Station",
      "Marka Police Station",
      "Markundi Police Station",
      "Mataundh Police Station",
      "Mau Police Station",
      "Naraini Police Station",
      "Pahari Police Station",
      "Pailani Police Station",
      "Raipura Police Station",
      "Rajapura Police Station",
      "Tindwari Police Station"
    ],
    "Barabanki": [
      "Anti Power Theft Thana Barabanki",
      "Anti-human Trafficking Unit Police Station",
      "Asandra Police Station",
      "Baddupur Police Station",
      "Badosarai Police Station",
      "Dariyabad Police Station",
      "Dewa Police Station",
      "Fatehpur Police Station",
      "GRP Barabanki Police Station",
      "Ghunghter Police Station",
      "Haider Garh Police Station",
      "Jaidpur Police Station",
      "Jhangirabad Police Station",
      "Kothi Police Station",
      "Kotwali Police Station",
      "Kursi Police Station",
      "Lonikatra Police Station",
      "Mahila Thana Barabanki",
      "Masauli Police Station",
      "Mawai Police Station",
      "Mohammadpur Khala Police Station",
      "Patranga Police Station",
      "Ram Sanehighat Police Station",
      "Ramnagar Police Station",
      "Rudauli Police Station",
      "Safdarganj Police Station",
      "Satrikh Police Station",
      "Subeha Police Station",
      "Tikait Nagar Police Station"
    ],
    "Bareilly": [
      "Aliganj Police Station",
      "Aonla Police Station",
      "Baheri Police Station",
      "Baradari Police Station",
      "Bhamora Police Station",
      "Bhojipura Police Station",
      "Bhuta Police Station",
      "Bitharichainpur Police Station",
      "Cantt Police Station",
      "Collector Bukganj Police Station",
      "Deorania Police Station",
      "Faridpur Police Station",
      "Fatehganj East Police Station",
      "Fatehganj West Police Station",
      "Hafizganj Police Station",
      "Izat Nagar Police Station",
      "Kotwali Police Station",
      "Meerganj Police Station",
      "Nawabganj Police Station",
      "Prem Nagar Police Station",
      "Qilla Police Station",
      "Quolaria Police Station",
      "Shahi Police Station",
      "Sheeshgarh Police Station",
      "Shergarh Police Station",
      "Sirauli Police Station",
      "Subhash Nagar Police Station",
      "Vishrat Ganj Police Station"
    ],
    "Basti": [
      "Belghat Police Station",
      "Belipar Police Station",
      "Bisauli Police Station",
      "Chhapia Police Station",
      "Chhawani Police Station",
      "Colonelganj Police Station",
      "Cyber Crime P.S. Basti Police Station",
      "Dhanepur Police Station",
      "Dubaulia Police Station",
      "GRP Basti Police Station",
      "Gaisri Police Station",
      "Gaur Police Station",
      "Gaura Choraha Police Station",
      "Gola Police Station",
      "Gorakhnath Police Station",
      "Gulriha Police Station",
      "Harraiya Police Station",
      "Harriya Police Station",
      "Itiathok Police Station",
      "Jarwa Police Station",
      "Kalwari Police Station",
      "Kaptan Ganj Police Station",
      "Katra Bazar Police Station",
      "Kauria Police Station",
      "Khajni Police Station",
      "Kharagupur Police Station",
      "Khodare Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Police Station",
      "Lalganj Police Station",
      "Lalia Police Station",
      "Maharaj Ganj Police Station",
      "Mahila Thana",
      "Mankapur Police Station",
      "Moti Ganj Police Station",
      "Munderwa Police Station",
      "Nagar Police Station",
      "Nawabganj Police Station",
      "Paikaulia Police Station",
      "Panchperwa Police Station",
      "Paraspur Police Station",
      "Parasrampur Police Station",
      "Pipraich Police Station",
      "Purani Basti Police Station",
      "Rehra Bazar Police Station",
      "Rudhauli Police Station",
      "Sadulla Nagar Police Station",
      "Sonaha Police Station",
      "Tarabagnj Police Station",
      "Tulsipur Police Station",
      "Umri Begamganj Police Station",
      "Utraula Police Station",
      "Walter Ganj Police Station",
      "Wazirganj Police Station"
    ],
    "Bhadohi": [
      "Aligarhwa Police Station",
      "Anti Power Theft Thana Bhadohi",
      "Aurai Police Station",
      "Bansi Police Station",
      "Bhadohi Police Station",
      "Chauri Police Station",
      "Durga Ganj Police Station",
      "Golhaura Police Station",
      "Gopiganj Police Station",
      "Koirauna Police Station",
      "Kotwali Gyanpur Police Station",
      "Mahila Thana Bhadohi",
      "Oonj Police Station",
      "Suriayawn Police Station"
    ],
    "Bijnor": [
      "Afzalgarh Police Station",
      "Barhapur Police Station",
      "Chandpur Police Station",
      "Dhampur Police Station",
      "GRP Bijnor Police Station",
      "Haldaur Police Station",
      "Heempur Police Station",
      "Kalaghrh Police Station",
      "Kiratpur Police Station",
      "Kotwali City Police Station",
      "Kotwali Dehat Police Station",
      "Mahila Thana",
      "Mandawali Police Station",
      "Mandawar Police Station",
      "Nagal Police Station",
      "Nagina Dehat Police Station",
      "Nagina Police Station",
      "Najibabad Police Station",
      "Nehtaur Police Station",
      "Noorpur Police Station",
      "Rehar Police Station",
      "Seohara Police Station",
      "Sherkot Police Station",
      "Shiwala Kalan Police Station"
    ],
    "Budaun": [
      "Alapur Police Station",
      "Bilsi Police Station",
      "Binawar Police Station",
      "Bisauli Police Station",
      "Civil Lines Police Station",
      "Dataganj Police Station",
      "Dhanari Police Station",
      "Faizganj Behata Police Station",
      "GRP Police Station",
      "Government Railway Police Stattion Police Station",
      "Gunnaur Police Station",
      "Hazaratpur Police Station",
      "Islam Nagar Police Station",
      "Kanwar Gaon Police Station",
      "Kotwali Police Station",
      "Mahila Thana",
      "Moosa Jhag Police Station",
      "Mujariya Police Station",
      "Qadar Chauk Police Station",
      "Rajpura Police Station",
      "Sahaswan Police Station",
      "Ugheti Police Station",
      "Ujhani Police Station",
      "Usait Police Station",
      "Usawan Police Station",
      "Wazirganj Police Station",
      "Zarif Nagar Police Station"
    ],
    "Bulandshahr": [
      "Agota Police Station",
      "Ahar Police Station",
      "Ahmad Garh Police Station",
      "Anoop Shahar Police Station",
      "Arnia Police Station",
      "Aurangabad Police Station",
      "Bhawan Bahadur Nagar Police Station",
      "Chhattri Police Station",
      "Debai Police Station",
      "Gulaothi Police Station",
      "Jahangir Pur Police Station",
      "Jahangirabad Police Station",
      "Jewar Police Station",
      "Kakore Police Station",
      "Kasna Police Station",
      "Khanpur Police Station",
      "Khurja Dehat Police Station",
      "Khurja Nagar Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Police Station",
      "Mahila Thana Bulandshahar",
      "Narora Police Station",
      "Narsena Police Station",
      "Pahasu Police Station",
      "Rabu Pura Police Station",
      "Ramghat Police Station",
      "Salempur Police Station",
      "Shikarpur Police Station",
      "Siana Police Station",
      "Sikandrabad Police Station"
    ],
    "Chandauli": [
      "Ali Nagar Police Station",
      "Baburi Police Station",
      "Bakhira Police Station",
      "Balua Police Station",
      "Chakia Police Station",
      "Chandauli Police Station",
      "Chhawani Police Station",
      "Dhanapur Police Station",
      "Dheena Police Station",
      "Dubaulia Police Station",
      "Dudhara Police Station",
      "Gaur Police Station",
      "Ghanghata Police Station",
      "Harraiya Police Station",
      "Illiya Police Station",
      "Kalwari Police Station",
      "Kandwa Police Station",
      "Kaptanganj Police Station",
      "Khalilabad Police Station",
      "Kotwali Police Station",
      "Lal Ganj Police Station",
      "Mahila Thana Alinagar",
      "Mahuli Police Station",
      "Mehdawal Police Station",
      "Mughal Sarai Police Station",
      "Munderwa Police Station",
      "Nagar Police Station",
      "Naugarh Police Station",
      "Paikaulia Police Station",
      "Parasrampur Police Station",
      "Purani Basti Police Station",
      "Rudhauli Police Station",
      "Saheb Ganj Police Station",
      "Sakaldiha Police Station",
      "Sonha Police Station",
      "Syedraja Police Station",
      "Walter Ganj Police Station"
    ],
    "Chitrakoot": [
      "Anti Power Theft Thana Chitrakoot",
      "Bahilpurwa Police Station",
      "Bargarh Police Station",
      "Bharatkoop Police Station",
      "G.R.P. Karwi Police Station",
      "G.R.P. Manikpur Police Station",
      "Karvi Police Station",
      "Mahila Thana",
      "Manikpur Police Station",
      "Markundi Police Station",
      "Mau Police Station",
      "Pahari Police Station",
      "Raipura Police Station",
      "Rajapur Police Station"
    ],
    "Deoria": [
      "A.r.t.o. Challani Police Station",
      "Ahirauli Bazar Police Station",
      "Baghauchghat Police Station",
      "Bankata Police Station",
      "Barhaj Police Station",
      "Barwa Patti Police Station",
      "Bhaluani Police Station",
      "Bhatni Police Station",
      "Bhatparrani Police Station",
      "Ekauna Police Station",
      "G. R. P. Bhatni Police Station",
      "G. R. P. Deoria Police Station",
      "Gauri Bazar Police Station",
      "Hanuman Ganj Police Station",
      "Hata Police Station",
      "Jatha Bazar Police Station",
      "Kaptangunj Police Station",
      "Kasia Police Station",
      "Khadda Police Station",
      "Khampar Police Station",
      "Khukhundu Police Station",
      "Kotwali, Deoria Police Station",
      "Kotwali, Rudrapur Police Station",
      "Kotwali, Salempur Police Station",
      "Kubersthan Police Station",
      "Lar Police Station",
      "Madanpur Police Station",
      "Mahila Thana",
      "Mail Police Station",
      "Nabua Naurangiya Police Station",
      "Padrauna Police Station",
      "Patherwa Police Station",
      "Ramkola Police Station",
      "Rampur Karkhana Police Station",
      "Sewrahi Police Station",
      "Tamkuhi Raj Police Station",
      "Tarkulwa Police Station",
      "Taryasujan Police Station",
      "Turkpatti Police Station",
      "Vishunpura Police Station"
    ],
    "Etah": [
      "Aliganj Police Station",
      "Anti Power Theft Thana Etah",
      "Awagarh Police Station",
      "Bagwala Police Station",
      "GRP Etah Police Station",
      "Jaithra Police Station",
      "Jalesar Police Station",
      "Jasrathpur Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Nagar Police Station",
      "Mahila Thana",
      "Malawan Police Station",
      "Marhara Police Station",
      "Mirhachi Police Station",
      "Nayagaon Police Station",
      "Nidholi Kalan Police Station",
      "Pilua Police Station",
      "Raja Ka Rampur Police Station",
      "Rijor Police Station",
      "Sakeet Police Station",
      "Sakrauli Police Station"
    ],
    "Etawah": [
      "Achhalda Police Station",
      "Airwakatra Police Station",
      "Ajitmal Police Station",
      "Anti Power Theft Thana Etawah",
      "Auraiya Police Station",
      "Ayana Police Station",
      "Bakewar Police Station",
      "Balrai Police Station",
      "Barhpura Police Station",
      "Basrehar Police Station",
      "Bela Police Station",
      "Bhareh Police Station",
      "Bharthana",
      "Bidhuna Police Station",
      "Bithauli Police Station",
      "Chakra Nagar Police Station",
      "Chaubia Police Station",
      "Civil Lines Police Station",
      "Dibiapur Police Station",
      "Ekdil Police Station",
      "Friends Colony Police Station",
      "GRP Etawah Police Station",
      "Jaswant Nagar Police Station",
      "Kotwali Police Station",
      "Lavedi Police Station",
      "Pachhay Gaon Police Station",
      "Phaphund Police Station",
      "Sahail Police Station",
      "Sahson Police Station",
      "Saiphai Police Station",
      "Usrahar Police Station",
      "Vedpura Police Station"
    ],
    "Farrukhabad": [
      "Amritpur Police Station",
      "Chhibramaupur Police Station",
      "Distt. Auriya Police Station",
      "Distt. Etawah Police Station",
      "Distt. Mainpuri Police Station",
      "Farrukhabad Police Station",
      "Fatehgarh Police Station",
      "G.R.P. Farrukhabad Police Station",
      "G.R.P. Fatehgarh Police Station",
      "G.R.P. Kaimganj Police Station",
      "G.R.P. Kasganj Police Station",
      "G.R.P. Mathura Police Station",
      "Gursahayaganj Police Station",
      "Indargarh Police Station",
      "Jahanganj Police Station",
      "Kalan Police Station",
      "Kamalganj Police Station",
      "Kampil Police Station",
      "Kannauj Police Station",
      "Kayamganj Police Station",
      "Mahila Thana Fatehgarh",
      "Maudarwaja Police Station",
      "Merapur Police Station",
      "Mirzapur Police Station",
      "Mohomdabad Police Station",
      "Nawabganj Police Station",
      "Paraur Police Station",
      "R. P. F. Kannauj Police Station",
      "R. P. F. Kasganj Police Station",
      "R. P. F. Mathura Police Station",
      "R.p.f. Farrukhabad Police Station",
      "R.p.f. Fatehgarh Police Station",
      "Rajepur Police Station",
      "Saurikh Police Station",
      "Shamshabad Police Station",
      "Sikandarpur Etah Police Station",
      "Talgarm Police Station",
      "Thathiya Police Station",
      "Tirwa Police Station",
      "Vishungarh Police Station"
    ],
    "Fatehpur": [
      "A.r.t.o. Police Station",
      "Anti Power Theft Thana",
      "Asother Police Station",
      "Aung Police Station",
      "Bakewar Police Station",
      "Bindki Police Station",
      "Chandpur Police Station",
      "Dhata Police Station",
      "G.R.P. Police Station",
      "Gazipur Police Station",
      "Hathgam Police Station",
      "Husainganj Police Station",
      "Jafarganj Police Station",
      "Jahanabad Police Station",
      "Kalyanpur Police Station",
      "Khaga Police Station",
      "Khakhareru Police Station",
      "Kishanpur Police Station",
      "Kotwali Sadar Police Station",
      "Lalauli Police Station",
      "Malwan Police Station",
      "Sultanpur Ghosh Police Station",
      "Thairyion Police Station",
      "Women Police Station"
    ],
    "Firozabad": [
      "Anti Power Theft Thana Firozabad",
      "Anti-human Trafficking Unit Police Station",
      "Basai Mohammadpur Police Station",
      "Eka Police Station",
      "Fariha Police Station",
      "Firozabad GRP Police Station",
      "Firozabad North Police Station",
      "Firozabad South Police Station",
      "Jasrana Police Station",
      "Khairgarh Police Station",
      "Linepar Police Station",
      "Mahila Police Station",
      "Makkhanpur Police Station",
      "Matsena Police Station",
      "Nagala Khangar Police Station",
      "Nagala Singhi Police Station",
      "Narkhi Police Station",
      "Nasir Pur Police Station",
      "Pachokhara Police Station",
      "Ramgarh Police Station",
      "Rasoolpur Police Station",
      "Shikohabad Police Station",
      "Sirsaganj Police Station",
      "Tundla GRP Police Station",
      "Tundla Police Station"
    ],
    "Ghaziabad": [
      "Babugarh Police Station",
      "Bahadur Garah Police Station",
      "Bhojpur Police Station",
      "Bisrikh Police Station",
      "Dadri Police Station",
      "Dhaulana Police Station",
      "GRP Police Station",
      "Garh Mukteshwar Police Station",
      "Ghaziabad Kotwali Police Station",
      "Hafizpur Police Station",
      "Hapud Police Station",
      "Hapur Police Station",
      "Indrapuram Police Station",
      "Jarcha Police Station",
      "Kaushambi Police Station",
      "Kavi Nagar Police Station",
      "Khoda Police Station",
      "Link Road Police Station",
      "Loni Border Police Station",
      "Loni Police Station",
      "Madhuban Bapudham Police Station",
      "Massorie Police Station",
      "Modi Nagar Police Station",
      "Murad Nagar Police Station",
      "Nandgram Police Station",
      "Niwari Police Station",
      "Noida Phase II Police Station",
      "Noida Sector 20 Police Station",
      "Noida Sector 24 Police Station",
      "Noida Sector 39 Police Station",
      "Noida Sector 49 Police Station",
      "Noida Sector 58 Police Station",
      "PS CBI",
      "Pilakhuwa Police Station",
      "Sahibabad Police Station",
      "Sihani Gate Police Station",
      "Simbhawali Police Station",
      "Surajgarh Police Station",
      "Teelamod Police Station",
      "Thana Mahila Gzb",
      "Tronica City Police Station",
      "Vijay Nagar Police Station"
    ],
    "Ghazipur": [
      "Antipowertheftthana Ghazipur",
      "Bahariyabad Police Station",
      "Baresar Police Station",
      "Bhawarkol Police Station",
      "Bhudkura Police Station",
      "Birno Police Station",
      "Dildarnagar Police Station",
      "Dulahpur Police Station",
      "Dullahpur Police Station",
      "GRP Ghazipur Police Station",
      "Gahmar Police Station",
      "Jungipur Police Station",
      "Karanda Police Station",
      "Karimuddinpur Police Station",
      "Kasimabad Police Station",
      "Khanpur Police Station",
      "Kotwali Police Station",
      "Mahila Thana Ghazipur",
      "Mardah Police Station",
      "Muhamadabad Police Station",
      "Nagsar Halt Police Station",
      "Nandganj Police Station",
      "Nonahara Police Station",
      "Reotipur Police Station",
      "Sadat Police Station",
      "Saidpur Police Station",
      "Shadiyabad Police Station",
      "Sonauli Police Station",
      "Suhawal Police Station",
      "Zamania Police Station"
    ],
    "Gonda": [
      "Bansgaon Police Station",
      "Barhalganj Police Station",
      "Belghat Police Station",
      "Cantt Police Station",
      "Chhapia Police Station",
      "Colonelganj Police Station",
      "Dhanepur Police Station",
      "GRP Police Station",
      "Intiyathok Police Station",
      "Katra Bazar Police Station",
      "Kauria Police Station",
      "Khargupur Police Station",
      "Khodarey Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Nagar Police Station",
      "Mahila Thana",
      "Mankapur Police Station",
      "Motiganj Police Station",
      "Nawabganj Police Station",
      "Paraspur Police Station",
      "Rpf Police Station",
      "Shahpur Police Station",
      "Tarabganj Police Station",
      "Umari Begamganj Police Station",
      "Wazirganj Police Station"
    ],
    "Gorakhpur": [
      "Aiims Police Station",
      "Anti Power Theft Thana Gorakhpur",
      "Anti-human Trafficking Police Station",
      "Badahalganj Police Station",
      "Bansgoan Police Station",
      "Bargadawa (Maharajganj) Police Station",
      "Belghat Police Station",
      "Belipar Police Station",
      "Campierganj Police Station",
      "Cantt Police Station",
      "Chaurichaura Police Station",
      "Chiluwatal Police Station",
      "Cyber Crime P.S. Gorakhpur Police Station",
      "Dumariyaganj(siddharthnagar) Police Station",
      "Farenda (Maharajganj) Police Station",
      "G.R.P. Gorakhpur Police Station",
      "GRP Anand Nagar Police Station",
      "GRP Basti Police Station",
      "Gagaha Police Station",
      "Ghughuli (Maharajganj) Police Station",
      "Gida Police Station",
      "Gola Police Station",
      "Gorakhnath Police Station",
      "Gulharia Police Station",
      "Harpur Budhat Police Station",
      "Jhagahan Police Station",
      "Kaudiram Police Station",
      "Khajani Police Station",
      "Khorabar Police Station",
      "Kotwali Police Station",
      "Mahila Thana",
      "Nautanawa (Maharajganj) Police Station",
      "Pipiganj Police Station",
      "Pipraich Police Station",
      "R.p.f Post Workshop Police Station",
      "R.p.f. Post Chhawani Police Station",
      "Rajghat Police Station",
      "Ramgarh Taal Police Station",
      "Sahjanawa Police Station",
      "Shahpur Police Station",
      "Sikariganj Police Station",
      "Tiwaripur Police Station",
      "Uruwa Police Station"
    ],
    "Hamirpur": [
      "Binwar Police Station",
      "Chikasi Police Station",
      "Jalalpur Police Station",
      "Jaria Police Station",
      "Khanna Police Station",
      "Kotwali Nagar Police Station",
      "Kurara Police Station",
      "Lalpura Police Station",
      "Mahila Thana",
      "Majhgawan Police Station",
      "Maudaha Police Station",
      "Muskara Police Station",
      "Rath Police Station",
      "Sisolar Police Station",
      "Sumerpur Police Station"
    ],
    "Hapur": [
      "Anti Power Theft Thana Hapur",
      "Babugarh Police Station",
      "Bahadur Garah Police Station",
      "Dhaulana Police Station",
      "Garh Mukteshwar Police Station",
      "Hafizpur Police Station",
      "Hapur Dehat Police Station",
      "Hapur Kotwali Police Station",
      "Mahila Thana Hapur",
      "Pilakhuwa Police Station",
      "Simbhawali Police Station"
    ],
    "Hardoi": [
      "Anti Human Tracking Unit Police Station",
      "Arbal Police Station",
      "Atrauli Police Station",
      "Baghauli Police Station",
      "Behta Gokul Police Station",
      "Beniganj Police Station",
      "Bilgram Police Station",
      "GRP Hardoi Police Station",
      "Hariyawan Police Station",
      "Harpalpur Police Station",
      "Kachhauna Police Station",
      "Kotwali City Police Station",
      "Kotwali Dehat Police Station",
      "Lonar Police Station",
      "Madhoganj Police Station",
      "Mahila Thana",
      "Mallawan Police Station",
      "Manjhila Police Station",
      "Pali Police Station",
      "Panchdeora Police Station",
      "Pihani Police Station",
      "Qasimpur Police Station",
      "Sandi Police Station",
      "Sandila Police Station",
      "Shahbad Police Station",
      "Sursa Police Station",
      "Tandiawan Police Station"
    ],
    "Hathras": [
      "Anti Power Theft Thana, Hathras",
      "Chandpa Police Station",
      "GRP Hathras City Police Station",
      "Hassain Police Station",
      "Hathras Gate Police Station",
      "Hathras Junction Police Station",
      "Hathras Police Station",
      "Iglas Police Station",
      "Mahila Thana",
      "Mursan Police Station",
      "Sadabad Police Station",
      "Sahpau Police Station",
      "Sasni Police Station",
      "Sikandra Rao Police Station"
    ],
    "Jalaun": [
      "Ait Police Station",
      "Ata Police Station",
      "Churkhi Police Station",
      "Dakaur Police Station",
      "Gohan Police Station",
      "Jalaun Police Station",
      "Kadaura Police Station",
      "Kailia Police Station",
      "Kalpi Police Station",
      "Konch Police Station",
      "Kotar Police Station",
      "Kotwali Orai Police Station",
      "Kuthaund Police Station",
      "Madhogarh Police Station",
      "Nadigaon Police Station",
      "Rampura Police Station",
      "Rendhar Police Station",
      "Sirsa Kalar Police Station"
    ],
    "Jaunpur": [
      "Anti-human Trafficking Unit Police Station",
      "Badlapur Police Station",
      "Baghichghat Police Station",
      "Baksa Police Station",
      "Bankata Police Station",
      "Barhaj Police Station",
      "Barsathi Police Station",
      "Bhaluani Police Station",
      "Bhatni Police Station",
      "Bhatpar Rani Police Station",
      "Chandawak Police Station",
      "G.R.P. Jaunpur Police Station",
      "Gaura Badshahpur Police Station",
      "Gauri Bazar Police Station",
      "Ikauna Police Station",
      "Jalalpur Police Station",
      "Kerakat Police Station",
      "Khampar Police Station",
      "Kheta Sarai Police Station",
      "Khukhundu Police Station",
      "Khuthan Police Station",
      "Kotwali Police Station",
      "Lar Police Station",
      "Line Bazar Police Station",
      "Machhali Shahar Police Station",
      "Madan Pur Police Station",
      "Maharaj Ganj Police Station",
      "Mahila Thana",
      "Mail Police Station",
      "Mariyahun Police Station",
      "Meerganj Police Station",
      "Mugra Badshahpur Police Station",
      "Newaria Police Station",
      "Pawara Police Station",
      "Rampur Kar Khana Police Station",
      "Rampur Police Station",
      "Rudrapur Police Station",
      "Salempur Police Station",
      "Sarai Khwaja Police Station",
      "Sarpataha Police Station",
      "Shahganj Police Station",
      "Sigra Mau Police Station",
      "Sikrara Police Station",
      "Sujanganj Police Station",
      "Sureri Police Station",
      "Zafrabad Police Station"
    ],
    "Jhansi": [
      "Anti Power Theft Thana Jhansi",
      "Anti-human Trafficking Unit Police Station",
      "Babina Police Station",
      "Baragaon Police Station",
      "Barwa Sagar Police Station",
      "Chirgaon Police Station",
      "Cyber Crime P.S. Jhansi Police Station",
      "Erich Police Station",
      "GRP Jhansi Police Station",
      "Garotha Police Station",
      "Gur Sarai Police Station",
      "Jhansi-sector (vigilance Estt.) Police Station",
      "Kakarwai Police Station",
      "Katera Police Station",
      "Kotwali Police Station",
      "Lehchura Police Station",
      "Mahila Thana",
      "Mauranipur Police Station",
      "Moth Police Station",
      "Nawabad Police Station",
      "Poonch Police Station",
      "Prem Nagar Police Station",
      "Raksa Police Station",
      "Sadar Bazar Police Station",
      "Sakrar Police Station",
      "Samthar Police Station",
      "Shahjhanpur Police Station",
      "Sipri Bazar Police Station",
      "Tehrauli Police Station",
      "Todi Fatehpur Police Station",
      "Uldan Police Station"
    ],
    "Kannauj": [
      "Bishun Garh Police Station",
      "Chhibramau Police Station",
      "Gursahaiganj Police Station",
      "Indergarh Police Station",
      "Kotwali Kannauj Police Station",
      "Mahila Police Station",
      "Saurikh Police Station",
      "Talgram Police Station",
      "Thathia Police Station",
      "Tirwa Police Station"
    ],
    "Kanpur Dehat": [
      "Akbarpur Police Station",
      "Amrahat Police Station",
      "Baraur Police Station",
      "Bhognipur Police Station",
      "Bilhaur Police Station",
      "Chaubepur Police Station",
      "Derapur Police Station",
      "Devrahat Police Station",
      "Gajner Police Station",
      "Ghatampur Police Station",
      "Kakwan Police Station",
      "Mahila Thana",
      "Mangalpur Police Station",
      "Moosa Nagar Police Station",
      "Rajpur Police Station",
      "Rasulabad Police Station",
      "Rura Police Station",
      "Saadh Police Station",
      "Sajeti Police Station",
      "Satti Police Station",
      "Shivli Police Station",
      "Shivrajpur Police Station",
      "Sikandara Police Station"
    ],
    "Kanpur Nagar": [
      "Anti Power Theft Police Station",
      "Anti-human Trafficking Unit Police Station",
      "Anwarganj Police Station",
      "Armapur Police Station",
      "Babu Purwa Police Station",
      "Badshahi Naka Police Station",
      "Bajaria Police Station",
      "Barra Police Station",
      "Bekan Ganj Police Station",
      "Bidhnoo Police Station",
      "Bithoor Police Station",
      "Cantt Police Station",
      "Chakeri Police Station",
      "Chaman Ganj Police Station",
      "Chaubeypur Police Station",
      "Coliector Ganj Police Station",
      "Colonol Ganj Police Station",
      "Fazalganj Police Station",
      "Feelkhana Police Station",
      "GRP Kanpur Nagar Police Station",
      "Govind Nagar Police Station",
      "Gwaltoli Police Station",
      "Harbans Mohal Police Station",
      "Juhi Police Station",
      "Kakadeo Police Station",
      "Kalyanpur Police Station",
      "Kidwai Nagar Police Station",
      "Kohna Police Station",
      "Kotwali Police Station",
      "Maharajpur Police Station",
      "Mahila Thana",
      "Mool Ganj Police Station",
      "Narwal Police Station",
      "Naubasta Police Station",
      "Nawabganj Police Station",
      "Nazirabad Police Station",
      "Panki Police Station",
      "Railbazar Police Station",
      "Raipurwa Police Station",
      "Sachendi Police Station",
      "Sisamau Police Station",
      "Swarup Nagar Police Station"
    ],
    "Kasganj": [
      "Ahraula Police Station",
      "Amapur Police Station",
      "Atraulia Police Station",
      "Bardah Police Station",
      "Bilariaganj Police Station",
      "Deogaon Police Station",
      "Dholna Police Station",
      "Didarganj Police Station",
      "GRP Kasganj Police Station",
      "Ganjdunddwara Police Station",
      "Ghambirpur Police Station",
      "Jahanganj Police Station",
      "Jeanpur Police Station",
      "Kandhrapur Police Station",
      "Kaptan Ganj Police Station",
      "Kasganj Police Station",
      "Kisaund(sunngarhi) Police Station",
      "Kotwali Police Station",
      "Mahila Thana",
      "Mahraj Ganj Police Station",
      "Mehnagar Police Station",
      "Mehnajpur Police Station",
      "Mubarkpur Police Station",
      "Nizamabad Police Station",
      "Patiali Police Station",
      "Pawai Police Station",
      "Phool Pur Police Station",
      "Rani-ki-sarai Police Station",
      "Raunapar Police Station",
      "Sahawar Police Station",
      "Saraimeer Police Station",
      "Sidhari Police Station",
      "Sikanderpur Vaish Police Station",
      "Sirhpura Police Station",
      "Souron Police Station",
      "Tahabarpur Police Station",
      "Tarwa Police Station"
    ],
    "Kaushambi": [
      "Charwa Police Station",
      "Kada Police Station",
      "Karari Police Station",
      "Kaushambi Police Station",
      "Kokhraj Police Station",
      "Mahewa Ghat Police Station",
      "Mahila Thana",
      "Manjhanpur Police Station",
      "Mohd. Painsa Police Station",
      "Pachim Sarira Police Station",
      "Pipari Police Station",
      "Puramufti Police Station",
      "Saini Police Station",
      "Sarai Aqil Police Station"
    ],
    "Kushinagar": [
      "Ahirauli Bazar Police Station",
      "Anti Human Trafficking Unit Police Station",
      "Barwa Patti Police Station",
      "Hanumanganj Police Station",
      "Jatahan Bazar Police Station",
      "Kaptanganj Police Station",
      "Kasya Police Station",
      "Khadda Police Station",
      "Kotwali Hata Police Station",
      "Kotwali Padrauna Police Station",
      "Kuber Sthan Police Station",
      "Mahila Thana Kushinagar",
      "Nebua Naurangia Police Station",
      "Pataherwa Police Station",
      "Ramkola Police Station",
      "Sevrahi Police Station",
      "Tarya Sujan Police Station",
      "Turka Patti Police Station",
      "Vishunpura Police Station"
    ],
    "Lakhimpur Kheri": [
      "Bhira Police Station",
      "Chandan Chauki Police Station",
      "Dhaurahra Police Station",
      "GRP Lakhimpur Police Station",
      "GRP Police Station",
      "Gaurifanta Police Station",
      "Gola Police Station",
      "Haidrabad Police Station",
      "Isanagar Police Station",
      "Khiri Police Station",
      "Kotwali Police Station",
      "Mahila Thana.",
      "Maigalganj Police Station",
      "Mailani Police Station",
      "Mitauli Police Station",
      "Mohammadi Police Station",
      "Neemgaon Police Station",
      "Nighasan Police Station",
      "Palia Police Station",
      "Pasgawan Police Station",
      "Phardhan Police Station",
      "Phool Behar Police Station",
      "Sampurna Nagar Police Station",
      "Singahi Police Station",
      "Tikonia Police Station"
    ],
    "Lalitpur": [
      "Bala Behat Police Station",
      "Banpur Police Station",
      "Bar Police Station",
      "GRP Lalitpur Police Station",
      "Girrar Police Station",
      "Jakhalaun Police Station",
      "Jakhaura Police Station",
      "Kotwali Lalitpur Police Station",
      "Madanpur Police Station",
      "Madawara Police Station",
      "Mahila Thana",
      "Mahrauni Police Station",
      "Narahat Police Station",
      "Pali Police Station",
      "Poora Kalan Police Station",
      "Sojana Police Station",
      "Tal Behat Police Station"
    ],
    "Lucknow": [
      "ATS Police Station",
      "Alambagh Police Station",
      "Aliganj Police Station",
      "Aminabad Police Station",
      "Ashiyana Police Station",
      "Baksi Ka Talab Police Station",
      "Banthara Police Station",
      "Bazar Khala Police Station",
      "Cantt Police Station",
      "Chinhat Police Station",
      "Chowk Police Station",
      "Cyber Crime Police Station",
      "G.R.P. Police Station",
      "Gautampalli Police Station",
      "Gazipur Police Station",
      "Godamba Police Station",
      "Gomti Nagar Police Station",
      "Gomti Nagar Vistar Police Station",
      "Gosainganj Police Station",
      "Hasan Ganj Police Station",
      "Hazratganj Police Station",
      "Husainganj Police Station",
      "Indira Nagar Police Station",
      "Itaunja Police Station",
      "Jankipuram Police Station",
      "Kakori Police Station",
      "Krishna Nagar Police Station",
      "Mahanagar Police Station",
      "Mahila Thana",
      "Malihabad Police Station",
      "Mall Police Station",
      "Manak Nagar Police Station",
      "Mandion Police Station",
      "Mohan Lal Ganj Police Station",
      "Nagram Police Station",
      "Naka Hindola Police Station",
      "Nigoha Police Station",
      "Para Police Station",
      "Pgi Police Station",
      "Qaiser Bagh Police Station",
      "R.p.f. Police Station",
      "Saadatganj Police Station",
      "Sarojini Nagar Police Station",
      "Sushant Golf City Police Station",
      "Tal Katora Police Station",
      "Thakur Ganj Police Station",
      "Vibhuti Khand Police Station",
      "Vikas Nagar Police Station",
      "Wazirganj Police Station"
    ],
    "Maharajganj": [
      "Bargadwa Police Station",
      "Brijmanganj Police Station",
      "Chawk Police Station",
      "G.R.P. (anand Nagar) Police Station",
      "Ghughuli Police Station",
      "Kolhui Police Station",
      "Kothibhar Police Station",
      "Kotwali (Sadar) Police Station",
      "Kotwali (Sonauli) Police Station",
      "Kotwali (Thuthibari) Police Station",
      "Nautanwa Police Station",
      "Nichlaul Police Station",
      "Paniyara Police Station",
      "Parsa Malik Police Station",
      "Pharenda Police Station",
      "Purandarpur Police Station",
      "Shyamdeurwa Police Station",
      "Sohgibarwa Police Station"
    ],
    "Mahoba": [
      "Ajnar Police Station",
      "Anti Power Theft Thana Mahoba",
      "Charkhari Police Station",
      "G.R.P. Mahoba Police Station",
      "Kabrai Police Station",
      "Khanna Police Station",
      "Kharela Police Station",
      "Kulpahar Police Station",
      "Mahila Thana",
      "Mahoba Police Station",
      "Mahobakanth Police Station",
      "Panwari Police Station",
      "Srinagar Police Station",
      "Thana Khanna"
    ],
    "Mainpuri": [
      "Allau Police Station",
      "Anti Power Theft Thana Mainpuri",
      "Barnahal Police Station",
      "Bewar Police Station",
      "Bhogaon Police Station",
      "Dannahar Police Station",
      "Ghiror Police Station",
      "Karhal Police Station",
      "Kishni Police Station",
      "Kotwali Police Station",
      "Kuraoli Police Station",
      "Kurrah Police Station",
      "Oncha Police Station",
      "Vichawan Police Station"
    ],
    "Mathura": [
      "Baldeo Police Station",
      "Barsana Police Station",
      "Chhata Police Station",
      "Farah Police Station",
      "GRP Police Station",
      "Govardhan Police Station",
      "Govind Nagar Police Station",
      "Kosi Police Station",
      "Kotwali Police Station",
      "Mahavan Police Station",
      "Mahila Thana",
      "Manth Police Station",
      "Mogarrah Police Station",
      "Narhauli (Highway) Police Station",
      "Naujhil Police Station",
      "Raya Police Station",
      "Refinery Police Station",
      "Rpf Police Station",
      "Sadabad Police Station",
      "Sadar Bazar Police Station",
      "Sahpau Police Station",
      "Shergarh Police Station",
      "Surir Police Station",
      "Telshodhkarkhana Police Station",
      "Vrindavan Police Station",
      "Yamunapar Police Station"
    ],
    "Mau": [
      "Badlapur Police Station",
      "Baksa Police Station",
      "Barsathi Police Station",
      "Chandawak Police Station",
      "Chiraiyakot Police Station",
      "Dakshintola Police Station",
      "Doharighat Police Station",
      "G.R.P. Mau Police Station",
      "Gaura Badshahpur Police Station",
      "Ghosi Police Station",
      "Haldharpur Police Station",
      "Jalalpur Police Station",
      "Kerakat Police Station",
      "Kheta Sarai Police Station",
      "Khuthan Police Station",
      "Kopa Ganj Police Station",
      "Kotwali Mau Police Station",
      "Kotwali Police Station",
      "Line Bazar Police Station",
      "Machhali Shahar Police Station",
      "Madhuban Police Station",
      "Maharaj Ganj Police Station",
      "Mahila Thana",
      "Mariyahun Police Station",
      "Meerganj Police Station",
      "Mohammadabad Police Station",
      "Mugra Badshahpur Police Station",
      "Newaria Police Station",
      "Pawara Police Station",
      "Rampur Police Station",
      "Ranipur Police Station",
      "Sarai Khwaja Police Station",
      "Sarai Lakhansi Police Station",
      "Sarpataha Police Station",
      "Shahganj Police Station",
      "Sigra Mau Police Station",
      "Sikrara Police Station",
      "Sujanganj Police Station",
      "Sureri Police Station",
      "Zafrabad Police Station"
    ],
    "Meerut": [
      "Ahtu Police Station",
      "Aminagar Sarai Police Station",
      "Bahsuma Police Station",
      "Balaini Police Station",
      "Baraut Police Station",
      "Bhawanpur Police Station",
      "Binauli Police Station",
      "Brahampuri Police Station",
      "Chandi Nagar Police Station",
      "Chhaprauli Police Station",
      "Civil Lines Police Station",
      "Daurala Police Station",
      "Delhi Gate Police Station",
      "Doghat Police Station",
      "Falawda Police Station",
      "G.r.p Police Station",
      "Ganganagar Police Station",
      "Hastinapur Police Station",
      "Inchauli Police Station",
      "Jani Police Station",
      "Kanker Khera Police Station",
      "Kharkhauda Police Station",
      "Khekra Police Station",
      "Kithore Police Station",
      "Kotwali Police Station",
      "Lal Kurti Police Station",
      "Lisarigate Police Station",
      "Mahila Thana",
      "Mawana Police Station",
      "Medical Police Station",
      "Mundali Police Station",
      "Nauchandi Police Station",
      "Pallavpuram Police Station",
      "Parikshatgarh Police Station",
      "Partapur Police Station",
      "R.p.f. Police Station",
      "Railway Road Police Station",
      "Ramala Police Station",
      "Rohta Police Station",
      "Sadar Bazar Police Station",
      "Sardhana Police Station",
      "Saroorpur Police Station",
      "Transport Nagar Police Station"
    ],
    "Mirzapur": [
      "A.r.t.o. Chalan Police Station",
      "Adalhat Police Station",
      "Ahraura Police Station",
      "Chillh Police Station",
      "Chunar Police Station",
      "G.r.p Police Station",
      "Halia Police Station",
      "Jamalpur Police Station",
      "Jigina Police Station",
      "Kachhwa Police Station",
      "Katra Police Station",
      "Kotwali City Police Station",
      "Kotwali Dehat Police Station",
      "Lal Ganj Police Station",
      "Madihan Police Station",
      "Mahila Thana",
      "Pandri Police Station",
      "T.p.line Police Station",
      "Vindhyachal Police Station"
    ],
    "Moradabad": [
      "Adampur Police Station",
      "Amroha Dehat Police Station",
      "Amroha Police Station",
      "Anti Power Theft Thana Moradabad",
      "Asmoli Police Station",
      "Bachhrayun Police Station",
      "Bahjoi Police Station",
      "Baniather Police Station",
      "Bhagatpur Police Station",
      "Bhojpur Police Station",
      "Bilari Police Station",
      "Chajlet Police Station",
      "Chandausi Police Station",
      "Civil Lines Police Station",
      "Cyber Crime P.s Moradabad Police Station",
      "Dhanaura Mandi Police Station",
      "Didauli Police Station",
      "Dilari Police Station",
      "Fatehgarh Kurh Police Station",
      "GRP Moradabad Police Station",
      "Gajraula Police Station",
      "Golshahid Police Station",
      "Gunnaur Police Station",
      "Hasanpur Police Station",
      "Hayat Nagar Police Station",
      "Hazrat Nagar Garhi Police Station",
      "Kanth Police Station",
      "Katghar Police Station",
      "Kotwali Police Station",
      "Kundarki Police Station",
      "Mahila Thana",
      "Mainather Police Station",
      "Majhaula Police Station",
      "Moghalpura Police Station",
      "Moondha Pandey Police Station",
      "Nagphani Police Station",
      "Nakhasa Police Station",
      "Naugawan Sadat Police Station",
      "Pakvara Police Station",
      "R.p.f. Chandausi Police Station",
      "R.p.f. Gajraula Police Station",
      "R.p.f. Hapur Police Station",
      "R.p.f. Moradabad Police Station",
      "R.p.f. Rampur Police Station",
      "R.p.f. Rurki Police Station",
      "Rajjabpur Police Station",
      "Rpf Rampur Police Station",
      "Saidnagli Police Station",
      "Sambhal Police Station",
      "Sonakpur Police Station",
      "Thakurdwara Police Station"
    ],
    "Muzaffarnagar": [
      "Adarsh Mandi Shamli Police Station",
      "Babri Police Station",
      "Bhawan Police Station",
      "Bhopa Police Station",
      "Bhoran Kalan Police Station",
      "Budhana Police Station",
      "Charthawal Police Station",
      "Chhapar Police Station",
      "Civil Lines Police Station",
      "G.R.P. Muzaffarnagar Police Station",
      "Garhi Pukhta Police Station",
      "Jansath Police Station",
      "Jhinjhana Police Station",
      "Kairana Police Station",
      "Kakrauli Police Station",
      "Kandhla Police Station",
      "Khatauli Police Station",
      "Kotwali Nagar Police Station",
      "Mahila Thana",
      "Mansoor Pur Police Station",
      "Mirapur Police Station",
      "Nai Mandi Police Station",
      "Phugana Police Station",
      "Purkaji Police Station",
      "Ramraj Police Station",
      "Ratan Puri Police Station",
      "Shahapur Police Station",
      "Shamli Police Station",
      "Sikhera Police Station",
      "Titavi Police Station"
    ],
    "Noida / Gautam Buddha Nagar": [
      "A.r.t.o. Police Station",
      "Badalpur Police Station",
      "Bisrak Police Station",
      "Bisrikh Police Station",
      "Cyber Crime Police Station",
      "Dadri Police Station",
      "Dankaur Police Station",
      "Ecotech-1 Police Station",
      "Ecotech-iii Police Station",
      "Expressway Police Station",
      "Greater Noida/ Site V Police Station",
      "Jahangirpur Police Station",
      "Jarcha Police Station",
      "Jewar Police Station",
      "Kakore Police Station",
      "Kasna Police Station",
      "Kasna/beta II Police Station",
      "Knowledge Park Police Station",
      "Mahila Thana.",
      "Noida Sector-20 Police Station",
      "Noida Sector-24 Police Station",
      "Noida Sector-39 Police Station",
      "Noida Sector-49 Police Station",
      "Noida Sector-58 Police Station",
      "Phase-ii Police Station",
      "Phase-iii Police Station",
      "Rabupura Police Station",
      "Surajpur Police Station",
      "Traffic Police Noida Police Station"
    ],
    "Pilibhit": [
      "Amaria Police Station",
      "Anti Power Theft Police Station",
      "Anti-human Trafficking Unit Police Station",
      "Barahi Forest Range Police Station",
      "Barkhera Police Station",
      "Bilsanda Police Station",
      "Bisalpur Police Station",
      "Circle-i Police Station",
      "Diyoriyakalan Police Station",
      "G.R.P. Police Station",
      "Gajraula Police Station",
      "Hazara Police Station",
      "Jahanabad Police Station",
      "Kotwali Police Station",
      "Madhotanda Police Station",
      "Mahila Thana",
      "Mahof Forest Range Police Station",
      "Mala Forest Range Police Station",
      "Neoria Police Station",
      "Purakalandar Police Station",
      "Puranpur Police Station",
      "Sehramau North Police Station",
      "Sungarhi Police Station"
    ],
    "Pratapgarh": [
      "Antoo Police Station",
      "Aspur Deosara Police Station",
      "Baghrai Police Station",
      "Dileeppur Police Station",
      "Fatanpur Police Station",
      "G.R.P. Police Station",
      "Hathgwan Police Station",
      "Jathwara Police Station",
      "Kandhai Police Station",
      "Konhdaur Police Station",
      "Kotwali City Police Station",
      "Kunda Police Station",
      "Lalganj Police Station",
      "Leelapur Police Station",
      "Maheshganj Police Station",
      "Mahila Thana",
      "Mandhata Police Station",
      "Manikpur Police Station",
      "Nawabganj Police Station",
      "Patti Police Station",
      "Raniganj Police Station",
      "Sangipur Police Station",
      "Sangramgarh Police Station",
      "Udaipur Police Station"
    ],
    "Prayagraj (Allahabad)": [
      "Attarsuiya Police Station",
      "Baharia Police Station",
      "Bara Police Station",
      "Cantonment Police Station",
      "Charwa Police Station",
      "Civil Lines Police Station",
      "Colonalganj Police Station",
      "Daraganj Police Station",
      "Dhoomanganj Police Station",
      "G.R.P. Police Station",
      "George Town Police Station",
      "Ghoorpur Police Station",
      "Handia Police Station",
      "Hola Garh Police Station",
      "Industrial Area Police Station",
      "Jhunsi Police Station",
      "Karaili Scheme Police Station",
      "Karari Police Station",
      "Karchhana Police Station",
      "Kaseli Police Station",
      "Kaundhiyara Police Station",
      "Khiri Police Station",
      "Khuldabad Police Station",
      "Kokhraj Police Station",
      "Koraon Police Station",
      "Kosambi Police Station",
      "Kotwali Police Station",
      "Kydganj Police Station",
      "Lalapur Police Station",
      "Mahila Thana",
      "Manda Police Station",
      "Manjhanpur Police Station",
      "Mauaima Police Station",
      "Meja Police Station",
      "Mohabbatpur Police Station",
      "Muthiganj Police Station",
      "Naini Police Station",
      "Nawabaganj Police Station",
      "Pachhim Sarira Police Station",
      "Phoolpur Police Station",
      "Pipari Police Station",
      "Puramufti Police Station",
      "Saini Police Station",
      "Sarai Aqil Police Station",
      "Sarai Inayat Police Station",
      "Sarai Memrez Police Station",
      "Shahaganj Police Station",
      "Shankergarh Police Station",
      "Shivkuti Police Station",
      "Soraon Police Station",
      "Tharwai Police Station",
      "Utraon Police Station"
    ],
    "Raebareli": [
      "Anti Power Theft Thana Rae Bareli",
      "Bachhrawan Police Station",
      "Bhadokhar Police Station",
      "Dalmau Police Station",
      "Deeh Police Station",
      "Furshat Ganj Police Station",
      "Gadaganj Police Station",
      "Gurbuxganj Police Station",
      "Harchandpur Police Station",
      "Industrial Area Police Station",
      "Jagatpur Police Station",
      "Jais Police Station",
      "Khiron Police Station",
      "Kotwali Police Station",
      "Lalganj Police Station",
      "Maharajganj Police Station",
      "Mohanganj Police Station",
      "Nasirabad Police Station",
      "Salon Police Station",
      "Sareni Police Station",
      "Sheo Garh Police Station",
      "Sheoratanganj Police Station",
      "Unchahar Police Station"
    ],
    "Saharanpur": [
      "Bargaon Police Station",
      "Beharigarh Police Station",
      "Behat Police Station",
      "Chilkana Police Station",
      "Deoband Police Station",
      "Fatehpur Police Station",
      "GRP Police Station",
      "Gagal Heri Police Station",
      "Gangoh Police Station",
      "Janak Puri Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Nagar Police Station",
      "Kutubsher Police Station",
      "Mahila Thana",
      "Mandi Police Station",
      "Mirzapur Police Station",
      "Nagal Police Station",
      "Nakur Police Station",
      "Nanota Police Station",
      "Railaway Police Force Police Station",
      "Rampur Police Station",
      "Sadar Bazar Police Station",
      "Sarsawa Police Station",
      "Teetrion Police Station",
      "Traffic Police Police Station"
    ],
    "Sambhal": [
      "Anti Power Theft Sambhal Police Station",
      "Asmoli Police Station",
      "Bahjoi Police Station",
      "Baniather Police Station",
      "Chandausi Police Station",
      "Dhanari Police Station",
      "Fatehgarh Kurh Police Station",
      "Gunnaur Police Station",
      "Hajrat Nagar Garhi Police Station",
      "Hayat Nagar Police Station",
      "Mahila Thana",
      "Nakhasa Police Station",
      "Narvasa Police Station",
      "Rajapura Police Station",
      "Rajpura Police Station",
      "Sambhal Police Station"
    ],
    "Sant Kabir Nagar": [
      "Anti Power Theft Thana Sant Kabir Nagar",
      "Bakhira Police Station",
      "Belharkala Police Station",
      "Dhanghata Police Station",
      "Dharmsinghwa Police Station",
      "Dudhara Police Station",
      "Khalilabad Police Station",
      "Mahila Thana Skn",
      "Mahuli Police Station",
      "Menhdawal Police Station"
    ],
    "Shahjahanpur": [
      "Allahganj Police Station",
      "Banda Police Station",
      "G.R.P. Police Station",
      "Garhiya Rangeen Police Station",
      "Jaitipur Police Station",
      "Jalalabad Police Station",
      "Kalan Police Station",
      "Kanth Police Station",
      "Katra Police Station",
      "Khudaganj Police Station",
      "Khutar Police Station",
      "Kotwali Police Station",
      "Ladies Police Station",
      "Madanpura Police Station",
      "Mahila Thana",
      "Mirzapur Police Station",
      "Nigohi Police Station",
      "Paraur Police Station",
      "Powayan Police Station",
      "Ramchandra Misson Police Station",
      "Roja Police Station",
      "S M North Police Station",
      "S M South Police Station",
      "Sadar Bazar Police Station",
      "Sindhauli Police Station",
      "Tilhar Police Station"
    ],
    "Shamli": [
      "Adarsh Mandi Shamli Police Station",
      "Babari Police Station",
      "Bhawan Police Station",
      "GRP Shamli Police Station",
      "Garhi Pukhta Police Station",
      "Jhinjhana Police Station",
      "Kairana Police Station",
      "Kandhla Police Station",
      "Mahila Thana Shamli",
      "R.p.f Shamli Police Station",
      "Shamli Police Station"
    ],
    "Shravasti": [
      "Anti Power Theft Thana Shravasti",
      "Anti-human Trafficking Unit,bhinga Police Station",
      "Bhinga Police Station",
      "Bhinga Range Police Station",
      "Charda Range Police Station",
      "Dargah Sharif Police Station",
      "East Sohelva Range Police Station",
      "Gilaula Police Station",
      "Haridatt Nagar Grint Range Police Station",
      "Ikauna Police Station",
      "Kakardari Range Police Station",
      "Mahila Thana",
      "Malhipur Police Station",
      "Navin Modern Police Thana",
      "Nawabganj Police Station",
      "Risiya Police Station",
      "Shravasti Range Police Station",
      "Sirsiya Police Station",
      "Sonva Police Station",
      "West Sohelwa Range Police Station"
    ],
    "Siddharth Nagar": [
      "A.r.t.o. Siddharthnagar Police Station",
      "Anti Human Trafficking Unit Police Station",
      "Anti Power Theft Thana Siddharthnagar",
      "Bansi Police Station",
      "Bhawaniganj Police Station",
      "Chilhiya Police Station",
      "Dharamsinghwa Police Station",
      "Dhbbarua Police Station",
      "Domariaganj Police Station",
      "G.R.P. Police Station",
      "Golhaura Police Station",
      "Itwa Police Station",
      "Jogia Udaipur Police Station",
      "Kapilvastu(aligarhwah) Police Station",
      "Kathela Samay Mata Police Station",
      "Khbsharaha Police Station",
      "L.c.s. Barhani Police Station",
      "Lotan Police Station",
      "Mahila Thana",
      "Mishraulia Police Station",
      "Mohana Police Station",
      "Pathara Bazar Police Station",
      "Shivnagar Didai Police Station",
      "Shohratgarh Police Station",
      "Siddharthnagar Police Station",
      "Trilokpur Police Station",
      "Uska Bazar Police Station"
    ],
    "Sitapur": [
      "Anti Power Theft Thana Sitapur",
      "Anti-human Trafficking Unit Police Station",
      "Ataria Police Station",
      "Biswan Police Station",
      "G.R.P. Sitapur Police Station",
      "Hargaon Police Station",
      "Imalia Sultanpur Police Station",
      "Kamlapur Police Station",
      "Khairabad Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Police Station",
      "Laharpur Police Station",
      "Machrehta Police Station",
      "Mahila Thana",
      "Mahmudabad Police Station",
      "Maholi Police Station",
      "Manpur Police Station",
      "Mishrit Police Station",
      "Naimisharanya Police Station",
      "Pisawan Police Station",
      "Ramkot Police Station",
      "Rampur Kalan Police Station",
      "Rampur Mathura Police Station",
      "Rausa Police Station",
      "Sadarpur Police Station",
      "Sakran Police Station",
      "Sandhana Police Station",
      "Sidhauli Police Station",
      "Talgaon Police Station",
      "Tambaur Police Station",
      "Thangaon Police Station"
    ],
    "Sonbhadra": [
      "A.r.t.o. Police Station",
      "Anpara Police Station",
      "Anti Power Theft Police Station",
      "Babhani Police Station",
      "Beejpur Police Station",
      "Chopan Police Station",
      "Dudhi Police Station",
      "Ghorawal Police Station",
      "Hathinala Police Station",
      "Jugail Police Station",
      "Karma Police Station",
      "Kon Police Station",
      "Mahila Thana Robertsganj",
      "Manchi Police Station",
      "Myorpur Police Station",
      "Obra Police Station",
      "Pannuganj Police Station",
      "Pipari Police Station",
      "Raipur Police Station",
      "Rampurbarkoniya Police Station",
      "Robertsganj Police Station",
      "Shahganj Police Station",
      "Shaktinagar Police Station",
      "T.i. Police Station",
      "Wyndhamganj Police Station"
    ],
    "Sultanpur": [
      "Akhand Nagar Police Station",
      "Baldi Rai Police Station",
      "Bandhuakalan Police Station",
      "Bazar Shukul Police Station",
      "Chanda Police Station",
      "Dhammaur Police Station",
      "Dhanpatganj Police Station",
      "Dsotpur Police Station",
      "GRP Sultanpur Police Station",
      "Gauri Gang Police Station",
      "Gosaigang Police Station",
      "Halia Pur Police Station",
      "Jagdish Pur Police Station",
      "Jaisinghpur Police Station",
      "Jamo Police Station",
      "Kamrauli Police Station",
      "Karoundi Kala Police Station",
      "Kotwali Amethi Police Station",
      "Kotwali Dehat Police Station",
      "Kotwali Kadipur Police Station",
      "Kotwali Lambhua Police Station",
      "Kotwali Musafirkhana Police Station",
      "Kotwali Nagar Police Station",
      "Kurebhar Police Station",
      "Kurwar Police Station",
      "Mahila Thana Sultanpur",
      "Motigarpur Police Station",
      "Munsi Gang Police Station",
      "Piper Pur Police Station",
      "Ramganj Police Station",
      "Sangrampur Police Station"
    ],
    "Unnao": [
      "Achalganj Police Station",
      "Ajgain Police Station",
      "Asiwan Police Station",
      "Asoha Police Station",
      "Auras Police Station",
      "Bangermau Police Station",
      "Barasagwar Police Station",
      "Behata Mujavar Police Station",
      "Bighapur Police Station",
      "Bihar Police Station",
      "Dahi Police Station",
      "Fatehpur Chaurasi Police Station",
      "G R P Unnao Police Station",
      "Gangaghat Police Station",
      "Hasanganj Police Station",
      "Kotwali Police Station",
      "Mahila Thana",
      "Makhi Police Station",
      "Maurawan Police Station",
      "Purwa Police Station",
      "Safipur Police Station",
      "Sohra Mau Police Station"
    ],
    "Varanasi": [
      "A.h.t.u. Police Station",
      "Adampur Police Station",
      "Baragaon Police Station",
      "Bhelupur Police Station",
      "Cantt. Police Station",
      "Chaubeypur Police Station",
      "Chetganj Police Station",
      "Cholapur Police Station",
      "Chowk Police Station",
      "Cyber Crime Thana",
      "Dasaswamedh Police Station",
      "GRP Cantt. Police Station",
      "Jaitpura Police Station",
      "Jansa Police Station",
      "Kapsethi Police Station",
      "Kotwali Police Station",
      "Lalpur Pandeypur Police Station",
      "Lanka Police Station",
      "Lohta Police Station",
      "Luxa Police Station",
      "Mahila Thana",
      "Manduadih Police Station",
      "Mirzamurad Police Station",
      "Paryatak Police Station",
      "Phoolpur Police Station",
      "R.p.f. Police Station",
      "Ramnagar Police Station",
      "Rohania Police Station",
      "Sarnath Police Station",
      "Shivpur Police Station",
      "Sigra Police Station",
      "Sindhaura Police Station"
    ]
  },
  "Delhi": {
    "New Delhi": [
      "Connaught Place Police Station",
      "Parliament Street Police Station",
      "Chanakyapuri Police Station",
      "Tughlak Road Police Station",
      "Mandir Marg Police Station",
      "Barakhamba Road Police Station",
      "Tilak Marg Police Station"
    ],
    "North Delhi": [
      "Civil Lines Police Station",
      "Kashmere Gate Police Station",
      "Kotwali Chandni Chowk Police Station",
      "Maurice Nagar Police Station",
      "Roop Nagar Police Station",
      "Timarpur Police Station",
      "Sadarbazar Police Station",
      "Subzi Mandi Police Station"
    ],
    "South Delhi": [
      "Hauz Khas Police Station",
      "Saket Police Station",
      "Malviya Nagar Police Station",
      "Mehrauli Police Station",
      "Safdarjung Enclave Police Station",
      "Fatehpur Beri Police Station",
      "Neb Sarai Police Station"
    ],
    "South East Delhi": [
      "Lajpat Nagar Police Station",
      "Kalkaji Police Station",
      "Amar Colony Police Station",
      "Govindpuri Police Station",
      "Okhla Police Station",
      "New Friends Colony Police Station",
      "Badarpur Police Station",
      "Sarita Vihar Police Station"
    ],
    "South West Delhi": [
      "Vasant Vihar Police Station",
      "Vasant Kunj North Police Station",
      "Vasant Kunj South Police Station",
      "Delhi Cantt Police Station",
      "Sarojini Nagar Police Station",
      "South Campus Police Station"
    ],
    "Central Delhi": [
      "Pahar Ganj Police Station",
      "Darya Ganj Police Station",
      "Kamla Market Police Station",
      "Karol Bagh Police Station",
      "Prasad Nagar Police Station",
      "Rajinder Nagar Police Station",
      "IP Estate Police Station",
      "Chandni Mahal Police Station"
    ],
    "West Delhi": [
      "Rajouri Garden Police Station",
      "Punjabi Bagh Police Station",
      "Janakpuri Police Station",
      "Vikas Puri Police Station",
      "Tilak Nagar Police Station",
      "Kirti Nagar Police Station",
      "Hari Nagar Police Station",
      "Moti Nagar Police Station"
    ],
    "East Delhi": [
      "Preet Vihar Police Station",
      "Shakarpur Police Station",
      "Laxmi Nagar Police Station",
      "Kalyanpuri Police Station",
      "Mandawali Police Station",
      "Mayur Vihar Police Station",
      "Pandav Nagar Police Station",
      "Gazipur Police Station"
    ],
    "North East Delhi": [
      "Seelampur Police Station",
      "Jafrabad Police Station",
      "Bhajanpura Police Station",
      "Khajuri Khas Police Station",
      "Dayalpur Police Station",
      "Gokulpuri Police Station",
      "Jyoti Nagar Police Station"
    ],
    "North West Delhi": [
      "Model Town Police Station",
      "Ashok Vihar Police Station",
      "Mukherjee Nagar Police Station",
      "Adarsh Nagar Police Station",
      "Shalimar Bagh Police Station",
      "Keshav Puram Police Station",
      "Bharat Nagar Police Station"
    ],
    "Shahdara": [
      "Shahdara Police Station",
      "Vivek Vihar Police Station",
      "Farsh Bazar Police Station",
      "Anand Vihar Police Station",
      "Seemapuri Police Station",
      "GTB Enclave Police Station"
    ]
  },
  "Maharashtra": {
    "Mumbai City": [
      "Colaba Police Station",
      "Marine Drive Police Station",
      "Cuffe Parade Police Station",
      "Azad Maidan Police Station",
      "MRA Marg Police Station",
      "Dongri Police Station",
      "JJ Marg Police Station",
      "Byculla Police Station",
      "Agripada Police Station",
      "Nagpada Police Station",
      "Malabar Hill Police Station",
      "Gamdevi Police Station",
      "Tardeo Police Station",
      "Worli Police Station",
      "Dadra Police Station"
    ],
    "Mumbai Suburban": [
      "Bandra Police Station",
      "Khar Police Station",
      "Santacruz Police Station",
      "Juhu Police Station",
      "Vile Parle Police Station",
      "Andheri Police Station",
      "Oshiwara Police Station",
      "Versova Police Station",
      "Goregaon Police Station",
      "Malad Police Station",
      "Kandivali Police Station",
      "Borivali Police Station",
      "Kurla Police Station",
      "Ghatkopar Police Station",
      "Powai Police Station",
      "Cyber Crime BKC Police Station"
    ],
    "Pune": [
      "Shivajinagar Police Station",
      "Kothrud Police Station",
      "Deccan Gymkhana Police Station",
      "Hinjewadi Police Station",
      "Swargate Police Station",
      "Hadapsar Police Station",
      "Faraskhana Police Station",
      "Vishrambaug Police Station",
      "Bund Garden Police Station",
      "Khadki Police Station",
      "Viman Nagar Police Station"
    ],
    "Nagpur": [
      "Sitabuldi Police Station",
      "Sadar Police Station",
      "Dhantoli Police Station",
      "Ambazari Police Station",
      "Ganeshpeth Police Station",
      "Panchpaoli Police Station",
      "Kotwali Police Station Nagpur",
      "Lakadganj Police Station"
    ],
    "Thane": [
      "Thane Nagar Police Station",
      "Naupada Police Station",
      "Kopri Police Station",
      "Wagle Estate Police Station",
      "Vartak Nagar Police Station",
      "Rabodi Police Station",
      "Kalyan Police Station",
      "Dombivli Police Station"
    ]
  },
  "Karnataka": {
    "Bengaluru Urban": [
      "Cubbon Park Police Station",
      "Vidhana Soudha Police Station",
      "Commercial Street Police Station",
      "High Grounds Police Station",
      "Indiranagar Police Station",
      "Koramangala Police Station",
      "Whitefield Police Station",
      "HSR Layout Police Station",
      "Jayanagar Police Station",
      "JP Nagar Police Station",
      "Basavanagudi Police Station",
      "Ulsoor Police Station",
      "Malleswaram Police Station",
      "Rajajinagar Police Station",
      "Cyber Crime CID Bengaluru"
    ],
    "Mysuru": [
      "Devaraja Police Station",
      "Lashkar Police Station",
      "Nazarbad Police Station",
      "Mandi Police Station",
      "Saraswathipuram Police Station",
      "Jayalakshmipuram Police Station",
      "Kuvempunagar Police Station",
      "Vidyaranyapuram Police Station"
    ],
    "Hubballi-Dharwad": [
      "Suburban Police Station Hubballi",
      "Kasabapeth Police Station",
      "Gokul Road Police Station",
      "Dharwad Town Police Station",
      "Vidyagiri Police Station"
    ]
  },
  "Tamil Nadu": {
    "Chennai": [
      "Marina Police Station",
      "Mylapore Police Station",
      "T Nagar Police Station",
      "Anna Nagar Police Station",
      "Kilpauk Police Station",
      "Egmore Police Station",
      "Triplicane Police Station",
      "Royapettah Police Station",
      "Adyar Police Station",
      "Guindy Police Station",
      "Cyber Crime Wing Chennai"
    ],
    "Coimbatore": [
      "R S Puram Police Station",
      "Race Course Police Station",
      "Saibaba Colony Police Station",
      "Singanallur Police Station",
      "Peelamedu Police Station",
      "Gandhipuram Police Station"
    ],
    "Madurai": [
      "Thallakulam Police Station",
      "Vilakkuthoon Police Station",
      "Sellur Police Station",
      "Teppakulam Police Station",
      "SS Colony Police Station"
    ]
  }
};

/**
 * Returns all districts for a given state
 */
export function getDistrictsForState(state) {
  if (!state) return [];
  const dir = CIVIC_POLICE_DIRECTORIES[state];
  if (dir) return Object.keys(dir);
  return ['Central District', 'North District', 'South District', 'East District', 'West District'];
}

/**
 * Returns all police stations for a given state and district
 */
export function getPoliceStationsForDistrict(state, district) {
  if (!state || !district) return [];
  const stateDir = CIVIC_POLICE_DIRECTORIES[state];
  if (stateDir && stateDir[district]) {
    return stateDir[district];
  }
  // Loose matching for district naming variations (e.g. Allahabad vs Prayagraj)
  if (stateDir) {
    const matchedKey = Object.keys(stateDir).find(k => 
      k.toLowerCase().includes(district.toLowerCase()) || 
      district.toLowerCase().includes(k.toLowerCase())
    );
    if (matchedKey && stateDir[matchedKey]) {
      return stateDir[matchedKey];
    }
  }
  return [
    `Kotwali Police Station, ${district}`,
    `Civil Lines Police Station, ${district}`,
    `Cantonment Police Station, ${district}`,
    `Mahila Thana, ${district}`,
    `Cyber Crime Police Station, ${district}`
  ];
}

/**
 * Normalizes a police station name for uniform string comparison & storage
 */
export function normalizeStationName(name) {
  if (!name) return '';
  let cleaned = name.trim();
  if (!cleaned.toLowerCase().includes('police station') && !cleaned.toLowerCase().includes('thana') && !cleaned.toLowerCase().includes('ps ')) {
    cleaned = `${cleaned} Police Station`;
  }
  return cleaned;
}
